apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
    # Lancer "minikube tunnel" pour activer l'external-ip
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
